// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSM-xj_ktJnqzjgghfKS2iC9Px6Bi542o',
    appId: '1:1074241288848:web:3b36a484adbac071e47615',
    messagingSenderId: '1074241288848',
    projectId: 'matsnusing',
    authDomain: 'matsnusing.firebaseapp.com',
    storageBucket: 'matsnusing.appspot.com',
    measurementId: 'G-VB3PQCHFE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1GXTfV_FIlgnuVf7gUIkUuDRzTxyLbg0',
    appId: '1:1074241288848:android:5e86779ba5e4254ee47615',
    messagingSenderId: '1074241288848',
    projectId: 'matsnusing',
    storageBucket: 'matsnusing.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdywqgX9U3ZVellIWA67hxNUYrNQv3XXU',
    appId: '1:1074241288848:ios:1d7440ba377f119de47615',
    messagingSenderId: '1074241288848',
    projectId: 'matsnusing',
    storageBucket: 'matsnusing.appspot.com',
    iosClientId: '1074241288848-82p14ev99ljo016aj3i2oq6vh1f92660.apps.googleusercontent.com',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdywqgX9U3ZVellIWA67hxNUYrNQv3XXU',
    appId: '1:1074241288848:ios:1d7440ba377f119de47615',
    messagingSenderId: '1074241288848',
    projectId: 'matsnusing',
    storageBucket: 'matsnusing.appspot.com',
    iosClientId: '1074241288848-82p14ev99ljo016aj3i2oq6vh1f92660.apps.googleusercontent.com',
    iosBundleId: 'com.example.client',
  );
}
