name: CI
on:
  push:
    branches:
      - master
    paths:
      - client/**
  pull_request:
    branches:
      - master
    paths:
      - client/**
  workflow_dispatch:
    
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
            channel: 'stable'
      - name: 'Build and Deploy'
        working-directory: ./client
        env:
          API_BASE: ${{ secrets.API_BASE }}
        run: |
          echo 'API_URL='$API_BASE > .env
          flutter pub get
          flutter config --enable-web
          flutter build web
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MATSNUSING }}'
          projectId: matsnusing
          entryPoint: ./client
          channelId: dev-client
