name: CI
on:
  push:
    branches:
      - master
    paths:
      - folder/**
  pull_request:
    branches:
      - master
    paths:
      - folder/**
  workflow_dispatch:
    
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
            channel: 'dev'
      - name: 'Build and Deploy'
        working-directory: ./client
        run: |
          flutter pub get
          flutter config --enable-web
          flutter build web
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MATSNUSING }}'
          projectId: matsnusing
